#!/usr/bin/env python3
"""PreToolUse hook: keep writes out of generated and release-owned files.

Some files in this repository are not authored by hand:

  - CHANGELOG.md and package.json's `version` are written by semantic-release
    (.releaserc.js -> @semantic-release/changelog + @semantic-release/git).
  - pnpm-lock.yaml / package-lock.json are written by the package manager.
  - dist/ and coverage/ are build and test output.
  - .env holds credentials.

Editing any of them by hand desynchronises the repository from its automation,
and the damage surfaces at release time rather than at edit time.

Decisions:
  DENY — generated, release-owned, or secret-bearing.
  ASK  — package.json (dependency and script edits are legitimate; the `version`
         field is not, and only a human can tell which this is).

Emits the PreToolUse JSON decision on stdout and always exits 0.
"""

import json
import re
import sys
from datetime import datetime
from pathlib import Path

WRITE_TOOLS = {"Edit", "Write", "NotebookEdit", "MultiEdit"}

# (regex over the repo-relative path, rule id, reason)
DENY = [
    (r"(^|/)CHANGELOG\.md$",
     "changelog",
     "CHANGELOG.md is generated by semantic-release (@semantic-release/changelog). "
     "Hand edits are overwritten at the next release and desync the tags from the notes."),
    (r"(^|/)(pnpm-lock\.yaml|package-lock\.json|yarn\.lock)$",
     "lockfile",
     "Lockfiles are written by the package manager. Run the pnpm command instead of editing."),
    (r"(^|/)dist/",
     "dist",
     "dist/ is build output (`pnpm build`). Edit the source in src/ instead."),
    (r"(^|/)coverage/",
     "coverage",
     "coverage/ is test output. Edit the specs instead."),
    (r"(^|/)node_modules/",
     "node-modules",
     "node_modules/ is managed by pnpm. Edits vanish on the next install."),
    (r"(^|/)\.env$",
     "dotenv",
     ".env holds credentials and is gitignored. Edit .env.example instead."),
    (r"(^|/)\.git/",
     "git-internals",
     "Never write into .git/ directly."),
]

ASK = [
    (r"(^|/)package\.json$",
     "package-json",
     "package.json's `version` field is owned by semantic-release — hand-bumping it desyncs "
     "the registry from the git tags. Dependency and script edits are fine; confirm this is one."),
    (r"(^|/)\.releaserc\.js$",
     "releaserc",
     "Changing the release configuration changes how every future version is computed."),
    (r"(^|/)\.github/workflows/",
     "workflows",
     "Workflow changes affect CI and the release pipeline for everyone."),
]

LOG_DIR = Path.home() / ".claude" / "hooks-logs"


def log(decision: str, rule_id: str, path: str, data: dict) -> None:
    try:
        LOG_DIR.mkdir(parents=True, exist_ok=True)
        logfile = LOG_DIR / f"{datetime.now().strftime('%Y-%m-%d')}.jsonl"
        with open(logfile, "a") as fh:
            fh.write(json.dumps({
                "ts": datetime.now().isoformat(),
                "hook": "write-boundary",
                "decision": decision,
                "rule_id": rule_id,
                "path": path,
                "session_id": data.get("session_id", ""),
                "cwd": data.get("cwd", ""),
            }) + "\n")
    except Exception:
        pass


def relative_path(raw: str, cwd: str) -> str:
    """Normalise to a repo-relative POSIX path when possible."""
    if not raw:
        return ""
    path = Path(raw)
    if cwd:
        try:
            return path.resolve().relative_to(Path(cwd).resolve()).as_posix()
        except (ValueError, OSError):
            pass
    return path.as_posix()


def classify(path: str):
    for pattern, rule_id, reason in DENY:
        if re.search(pattern, path):
            return "deny", rule_id, reason
    for pattern, rule_id, reason in ASK:
        if re.search(pattern, path):
            return "ask", rule_id, reason
    return None, None, None


def emit(decision: str, reason: str) -> None:
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": decision,
            "permissionDecisionReason": reason,
        }
    }))


def main() -> int:
    try:
        data = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        return 0

    if data.get("tool_name") not in WRITE_TOOLS:
        return 0

    tool_input = data.get("tool_input", {})
    raw = tool_input.get("file_path") or tool_input.get("notebook_path") or ""
    if not raw:
        return 0

    path = relative_path(raw, data.get("cwd", ""))
    decision, rule_id, reason = classify(path)
    if decision is None:
        return 0

    log(decision, rule_id, path, data)
    label = "BLOCKED" if decision == "deny" else "CONFIRM"
    emit(decision, f"{label} [{rule_id}] {path} — {reason}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
