export const MCP_MODULE_OPTIONS = 'MCP_MODULE_OPTIONS';
export const MCP_LOGGING_OPTIONS = 'MCP_LOGGING_OPTIONS';
export const MCP_TRANSPORT_OPTIONS = 'MCP_TRANSPORT_OPTIONS';
export const MCP_SESSION_OPTIONS = 'MCP_SESSION_OPTIONS';
