name: Run Tests

on:
  pull_request:
    branches:
      - 'release/*'
      - 'hotfix/*'
      - 'develop'
  push:
    branches:
      - 'feature/*'
      - 'develop'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linter
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test

      - name: Run build verification
        run: pnpm run build
